### ISSUE TITLE
user_test.go Tests Fail | undefined: ModelSuite

### ISSUE THREAD

**Issue by zeknox** [gobuffalo/buffalo-auth#38] opened 2019-03-21 17:32 UTC
Hi! I’ve installed the `buffalo-auth` plugin using the command `go getgithub.com/gobuffalo/buffalo-auth`. This completes properly and the buffalo-auth command runs properly from my `$PATH`.

I've run the `buffalo-auth auth` command against my project and this has generated proper auth structure; however, when running the default tests which are generated its throwing multiple errors:
<pre>
$GOPATH/src/coke/models/user_test.go:7:11: undefined: ModelSuite
$GOPATH/src/coke/models/user_test.go:29:11: undefined: ModelSuite
$GOPATH/src/coke/models/user_test.go:48:11: undefined: ModelSuite
</pre>

Looking at the default code which is generated, the test functions are passing in the argument `(ms *ModelSuite)` but this is not defined in a location that the test is aware of.

I've been able to resolve this issue by modifying the default code to include the `ModelSuite` struct.
Original Code generated by buffalo-auth:
<pre>
package models_test

import (
	"coke/models"
)

func (ms *ModelSuite) Test_User_Create() {
	count, err := ms.DB.Count("users")
	ms.NoError(err)
	ms.Equal(0, count)

	u := &models.User{
		Email:                "mark@example.com",
		Password:             "password",
		PasswordConfirmation: "password",
	}
	ms.Zero(u.PasswordHash)

	verrs, err := u.Create(ms.DB)
	ms.NoError(err)
	ms.False(verrs.HasAny())
	ms.NotZero(u.PasswordHash)

	count, err = ms.DB.Count("users")
	ms.NoError(err)
	ms.Equal(1, count)
}

[... SNIP ...]
</pre>

Fixed code which addresses the undefined condition and allows tests to run properly and pass.  The primary additions are defining the struct and adding the additional import line.
<pre>
package models_test

import (
	"coke/models"

	"github.com/gobuffalo/suite"
)

type ModelSuite struct {
	*suite.Model
}

func (ms *ModelSuite) Test_User_Create() {
	count, err := ms.DB.Count("users")
	ms.NoError(err)
	ms.Equal(0, count)

	u := &models.User{
		Email:                "mark@example.com",
		Password:             "password",
		PasswordConfirmation: "password",
	}
	ms.Zero(u.PasswordHash)

	verrs, err := u.Create(ms.DB)
	ms.NoError(err)
	ms.False(verrs.HasAny())
	ms.NotZero(u.PasswordHash)

	count, err = ms.DB.Count("users")
	ms.NoError(err)
	ms.Equal(1, count)
}

[... SNIP ...]
</pre>

I'm curious if there is something I've done wrong in the way I've installed the plugin or generated the auth code.  Is this something the buffalo-auth auth generator should add to the `user_test.go` file by default?  Any insight on the proper work flow or testing process would be greatly appreciated.

**Comment by cmorbitzer** [comment] 2019-11-13 17:00
I can confirm this issue exists when `models_test.go`, where `ModelSuite` is defined, belongs to the `models` package instead of the `models_test` package. This seems to be the default behavior for apps created with `buffalo new`. This is fixed by changing `package models` in `models_test.go` to `package models_test`.

**Comment by paganotoni** [comment] 2019-11-13 21:20
This one was covered in v1.0.8. please give it a shot and keep us posted.

**Closed as completed by paganotoni** 2019-11-13 21:20 UTC

**Comment by cmorbitzer** [comment] 2019-11-13 22:26
@paganotoni That fixed it. Thanks!
